services:
  inception-next:
    container_name: inception_next
    image: 355355355/inception-next
    restart: on-failure
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - next_network
networks:
  next_network:
    driver: bridge
